services:
  mysql-test:
    image: "mysql:latest"
    container_name: "local-test-mysql"
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "go-echo-api"
      MYSQL_TCP_PORT: 3306
